stages:
- deploy

staging:
  stage: deploy
  image: ruby:2.4
  script:
  - apt-get update -yq
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=shalosh --api-key=$HEROKU_API_KEY
  only:
  - master
